kafkanodepool:
  - name: controller
    enabled: true
    replicas: 1
    roles: 
      - controller
    storage_type: jbod
    volumes_type: persistent-claim
    volume_class: longhorn
    volume_size: 1Gi
    volume_kraftMetadata: shared
    volume_deleteClaim: false
  
  - name: broker
    enabled: true
    replicas: 1
    roles: 
      - broker
    storage_type: jbod
    volumes_type: persistent-claim
    volume_class: longhorn
    volume_size: 1Gi
    volume_kraftMetadata: shared
    volume_deleteClaim: false

  - name: dual_role
    enabled: false
    replicas: 1
    roles: 
      - controller
      - broker
    storage_type: jbod
    volumes_type: persistent-claim
    volume_class: longhorn
    volume_size: 1Gi
    volume_kraftMetadata: shared
    volume_deleteClaim: false

kafka:
  name: my-cluster
  enabled: true
  version: 4.1.1
  metadataVersion: 4.1-IV1
  plain_text_svc_type: nodeport
  tls_svc_type: nodeport
  offset_topic_replication_factor: 1
  state_log_replication_factor: 1
  state_log_min_isr: 1
  default_replication_factor: 1
  min_insync_replicas: 1
  cruise_control: false



